name: expense_manager
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI + platform support
  cupertino_icons: ^1.0.8

  # Local DB (for expenses)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  crypto: ^3.0.3

  # Date and formatting
  intl: ^0.19.0

  # Charts
  fl_chart: ^0.66.2

  # Exporting CSV
  csv: ^5.0.2

  # File handling
  # file_picker: ^5.5.0  # Downgrade to a stable version that supports v2 embedding
  share_plus: ^7.2.1
  permission_handler: ^11.3.1

  # PDF generation
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For Hive model generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

  # Linting (optional, already present)
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true